# Generated by Django 4.2.5 on 2023-10-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can',
            name='chem_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='h_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='h_year_of_passing',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='hostel_fees',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='marks_hsc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='maths_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='merit_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='mht_cet',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='other_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='pcm_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='phy_mrks',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='pmobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='recipt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='recipt_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='s_year_of_passing',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='seat_no_hsc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='stud_mob',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='total_fees',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='can',
            name='yearly_income',
            field=models.BigIntegerField(null=True),
        ),
    ]
