# Generated by Django 4.2.5 on 2023-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_can_chem_mrks_alter_can_h_mrks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undertaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
    ]
