# Generated by Django 4.2.5 on 2023-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_undertaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can',
            name='sign_photo',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
        migrations.AlterField(
            model_name='can',
            name='stud_photo',
            field=models.ImageField(null=True, upload_to='app/images'),
        ),
    ]
