# Generated by Django 4.2.5 on 2023-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_can_sign_photo_alter_can_stud_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='can',
            name='adhar_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='allotment_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='c_validity_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='caste_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='hsc_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='mht_cet_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='can',
            name='ssc_photo',
            field=models.FileField(null=True, upload_to='app/images/<django.db.models.fields.CharField>'),
        ),
    ]
